
from ontobdc.a32.domain.port.machine import EtlProcessStatePort


class A3EtlProcessState(EtlProcessStatePort):
    """
    Enum representing the possible states of the A3 pipeline process.

    Matches the states referenced in the pipeline and follows the
    localization pattern.
    """
    UNDEFINED = "__undefined__"
    RECEIVED = "__received__"
    SANITIZED = "__sanitized__"
    TYPED = "__typed__"
    PARSED = "__parsed__"
    TRANSLATED = "__translated__"
    VALIDATED = "__validated__"
    REASONED = "__reasoned__"
    DISPATCHED = "__dispatched__"
    FEDERATED = "__federated__"

    def label(self, lang: str = "en") -> str:
        """
        Returns the human-friendly label for the state in the specified language.

        :param lang: Language code (default "en")
        :return: Translated label string
        """
        labels = {
            "en": {
                self.UNDEFINED: "Undefined",
                self.RECEIVED: "Received",
                self.SANITIZED: "Sanitized",
                self.TYPED: "Typed",
                self.PARSED: "Parsed",
                self.TRANSLATED: "Translated",
                self.VALIDATED: "Validated",
                self.REASONED: "Reasoned",
                self.DISPATCHED: "Dispatched",
                self.FEDERATED: "Federated",
            },
            "pt-br": {
                self.UNDEFINED: "Indefinido",
                self.RECEIVED: "Recebido",
                self.SANITIZED: "Sanitizado",
                self.TYPED: "Tipificado",
                self.PARSED: "Analisado",
                self.TRANSLATED: "Traduzido",
                self.VALIDATED: "Validado",
                self.REASONED: "Inferredo/Raciocinado",
                self.DISPATCHED: "Despachado",
                self.FEDERATED: "Federado",
            },
        }
        return labels.get(lang, labels["en"]).get(self, self.value)

    def description(self, lang: str = "en") -> str:
        """
        Returns the technical description for the state in the specified language.

        :param lang: Language code (default "en")
        :return: Translated description string
        """
        descriptions = {
            "en": {
                self.UNDEFINED: "Initial state before extraction begins",
                self.RECEIVED: "The package contains a raw.txt file",
                self.SANITIZED: "The package contains a cleaned.txt file after basic cleaning",
                self.TYPED: "The execution context defines the shape used for parsing",
                self.PARSED: "The package contains a parsed.json file generated by the LLM",
                self.TRANSLATED: "The package contains a graph.ttl file resulting from JSON to TTL conversion",
                self.VALIDATED: "The package contains an aproved.txt SHACL validation report",
                self.REASONED: "The package contains a strobo.ttl file after passing through a reasoner",
                self.DISPATCHED: "The package contains an dispatched.jsonld file, persisted as an event",
                self.FEDERATED: "The dataset contains a payload/documents/<hash>.jsonld file registered as an InternalDocument in index.ttl",
            },
            "pt-br": {
                self.UNDEFINED: "Estado inicial antes do processamento",
                self.RECEIVED: "O pacote contém o arquivo raw.txt original",
                self.SANITIZED: "O pacote contém um cleaned.txt após limpeza básica",
                self.TYPED: "O contexto de execucao define o shape usado no parsing",
                self.PARSED: "O pacote contém o parsed.json gerado pela LLM",
                self.TRANSLATED: "O pacote contém um graph.ttl após conversão de JSON para TTL",
                self.VALIDATED: "O pacote contém um relatório aproved.txt de validação SHACL",
                self.REASONED: "O pacote contém o strobo.ttl gerado após execução do reasoner",
                self.DISPATCHED: "O pacote contém um dispatched.jsonld persistido como evento final",
                self.FEDERATED: "O dataset contém um payload/documents/<hash>.jsonld registrado como InternalDocument no index.ttl",
            },
        }
        return descriptions.get(lang, descriptions["en"]).get(self, "")

    @staticmethod
    def get_state(state: str) -> "A3EtlProcessState":
        """
        Returns the enum value given a state name string.

        :param state: The name of the state (case-insensitive)
        :return: A3EtlProcessState enum value
        """
        return getattr(A3EtlProcessState, state.upper())
