from pathlib import Path

from ontobdc.view.adapter.dashboard import _PACKAGED_LOGO_PNG, _ensure_dashboard_assets


def _logo_png_path(container_path: Path) -> Path:
    return container_path / ".__ontobdc__" / "asset" / "infobim-view" / "logo.png"


def test_ensure_dashboard_assets_copies_the_packaged_logo_png(tmp_path: Path) -> None:
    _ensure_dashboard_assets(tmp_path)

    logo_png = _logo_png_path(tmp_path)
    assert logo_png.is_file()
    assert logo_png.read_bytes() == _PACKAGED_LOGO_PNG.read_bytes()


def test_ensure_dashboard_assets_resyncs_a_stale_logo(tmp_path: Path) -> None:
    # Dashboards generated by an older ontobdc-view (or before the packaged
    # logo existed at all) already have a logo.png on disk. Regenerating the
    # dashboard must refresh it to match the currently packaged branding
    # instead of leaving the stale file in place forever.
    logo_png = _logo_png_path(tmp_path)
    logo_png.parent.mkdir(parents=True)
    logo_png.write_bytes(b"stale-logo-from-an-older-release")

    _ensure_dashboard_assets(tmp_path)

    assert logo_png.read_bytes() == _PACKAGED_LOGO_PNG.read_bytes()


def test_ensure_dashboard_assets_is_idempotent_once_synced(tmp_path: Path) -> None:
    logo_png = _logo_png_path(tmp_path)

    _ensure_dashboard_assets(tmp_path)
    first_mtime = logo_png.stat().st_mtime_ns

    _ensure_dashboard_assets(tmp_path)

    assert logo_png.stat().st_mtime_ns == first_mtime


def test_ensure_dashboard_assets_writes_the_project_css(tmp_path: Path) -> None:
    _ensure_dashboard_assets(tmp_path)

    css_path = (
        tmp_path / ".__ontobdc__" / "asset" / "infobim-view" / "css" / "project_dashboard.css"
    )
    assert css_path.is_file()
